repos:
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.3.3
    hooks:
      - id: gdlint
        name: gdlint
        description: "gdlint – linter for GDScript"
        entry: gdlint
        language: python
        language_version: python3
        require_serial: true
        types: [gdscript]


  - repo: local
    hooks:
      - id: gdscript-precommit
        name: Lint & format GDScript
        description: |
          1) Run gdlint on staged `.gd` files
          2) Format staged `.gd` files with four-space indentation
          3) Re-stage each formatted file
        entry: >-
          bash -c '
            echo "⏳ Running GDScript pre-commit…";

            files=$(git diff --cached --name-only -- "*.gd")
            [ -z "$files" ] && exit 0

            gdlint $files
            gdformat --use-spaces=4 $files
            git add $files

            echo "✅ GDScript linting and formatting complete."
          ' --
        language: system
        pass_filenames: false
        stages: [pre-commit]
        always_run: true
